version: "3.9" # docker compose version; define the version of the docker-compose file format

services:
  app:
    build:
      context: . # where the Dockerfile is located, in this case in the root directory
      args:
        - DEV=true
    ports:
      - "8000:8000" # map the port 8000 of the container to the port 8000 of the host
    volumes:
      #- .:/app short version
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=devdb
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data

volumes:
  dev-db-data: